// api/_lib/pdfFieldMapping.ts
var BON_DRAFT_KEYS = [
  "clientNom",
  "clientPrenom",
  "clientDateNaissance",
  "clientNumeroCni",
  "clientAdresse",
  "ribTitulaire",
  "ribIban",
  "ribBic",
  "ribBanque",
  "clientEmail",
  "clientTelephone",
  "vehiculeModele",
  "vehiculeVin",
  "vehiculePremiereCirculation",
  "vehiculeKilometrage",
  "vehiculeCo2",
  "vehiculeChevaux",
  "vehiculePrix",
  "optionsMode",
  "optionsPrixTotal",
  "optionsDetailJson",
  "vehiculeCarteGrise",
  "vehiculeFraisReprise",
  "vehiculeRemise",
  "vehiculeFinancement",
  "vehiculeDateLivraison",
  "vehiculeReprise",
  "vehiculeCouleur",
  "vehiculeOptions",
  "acompte",
  "modePaiement",
  "apport",
  "organismePreteur",
  "montantCredit",
  "tauxCredit",
  "dureeMois",
  "clauseSuspensive",
  "vendeurNom",
  "vendeurNotes",
  "templateId"
];

// test-import.ts
console.log("Keys:", BON_DRAFT_KEYS.length);
